In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
a = [1,2,3,"hi"]
a

[1, 2, 3, 'hi']

In [7]:
np.array(a)

array(['1', '2', '3', 'hi'], dtype='<U21')

In [8]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
arr = np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [16]:
np.random.rand(10)

array([0.194178  , 0.96936055, 0.00996247, 0.02825328, 0.89606991,
       0.55069247, 0.24145317, 0.6940035 , 0.64607251, 0.018912  ])

In [17]:
np.random.randn(10)

array([-0.11071257,  0.5704925 ,  0.64305656,  0.83314235,  0.18686611,
       -1.00449941,  0.54600545, -1.42672207,  0.03973387,  0.57110804])

In [18]:
np.random.randint(12,20,10)

array([14, 16, 12, 14, 17, 15, 12, 15, 16, 18], dtype=int32)

In [20]:
l =  np.array([[1,2,3],[4,5,6],[7,8,9]])
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
l.shape

(3, 3)

In [22]:
np.sum(l,axis =0)

array([12, 15, 18])

In [23]:
np.sum(l,axis =1)

array([ 6, 15, 24])

In [24]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [25]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])