In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[1:3]

array([12, 13])

In [5]:
arr[3::2]

array([14, 16, 18, 20])

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr[3: ,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [16]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])