In [3]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [4]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [6]:
a1//a2

array([0, 0, 0, 0, 0])

In [7]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [5]:
a2 +10

array([16, 17, 18, 19, 20])

In [6]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [7]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
arr = arr[:4]
arr

array([1, 2, 3, 4])

In [9]:
arr*2

array([2, 4, 6, 8])

In [12]:
b = arr.copy()
b

array([1, 2, 3, 4])

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [15]:
A

array([[1, 2],
       [3, 4]])

In [16]:
B

array([[5, 6],
       [7, 8]])

In [17]:
A @ B

array([[19, 22],
       [43, 50]])

In [18]:
A.T

array([[1, 3],
       [2, 4]])

In [19]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [22]:
np.vstack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
np.hstack((a1,a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.column_stack((a1,a2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [27]:
c =np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [30]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]